#pragma once
#include <cmath>
#include <mutex>

#include "component.h"
#include "component_logger.h"
#include "message_bus.h"
#include "messages.h"

namespace sil {

class DOC_DESC("Thermal Service") ThermalService {
 public:
  using Subscribes = ipc::MsgList<ipc::MsgId::PhysicsTick, ipc::MsgId::EnvironmentData,
                                  ipc::MsgId::ThermalRequest, ipc::MsgId::ResetRequest>;
  using Publishes = ipc::MsgList<ipc::MsgId::ThermalData>;

  explicit ThermalService(ipc::MessageBus& bus) : bus_(bus), logger_("thermal") {
    ipc::bind_subscriptions(bus_, this);
  }

  void on_message(const ipc::PhysicsTickPayload& tick) {
    std::lock_guard lk{mu_};
    float dt_s = tick.dt_us / 1e6f;

    // Heat generated by motor based on RPM
    float motor_heat_rate = std::abs(tick.speed_rpm) * 0.005f;
    // Heat dissipated to environment
    float motor_cooling_rate = (motor_temp_c_ - ambient_temp_c_) * 0.05f;

    motor_temp_c_ += (motor_heat_rate - motor_cooling_rate) * dt_s;

    // Battery heat generated by current draw (simplistic approx based on RPM)
    float battery_heat_rate = std::abs(tick.speed_rpm) * 0.002f;
    float battery_cooling_rate = (battery_temp_c_ - ambient_temp_c_) * 0.02f;

    battery_temp_c_ += (battery_heat_rate - battery_cooling_rate) * dt_s;

    static uint32_t count = 0;
    if (++count % 100 == 0) {
      logger_.info("Motor Temp: %.1fC, Battery Temp: %.1fC", motor_temp_c_, battery_temp_c_);
    }
  }

  void on_message(const ipc::EnvironmentPayload& env) {
    std::lock_guard lk{mu_};
    ambient_temp_c_ = env.ambient_temp_c;
  }

  void on_message(const ipc::ResetRequestPayload&) {
    std::lock_guard lk{mu_};
    motor_temp_c_ = ambient_temp_c_;
    battery_temp_c_ = ambient_temp_c_;
    logger_.info("Thermal state reset");
  }

  void on_message(const ipc::ThermalRequestPayload&) {
    ipc::ThermalPayload p{};
    {
      std::lock_guard lk{mu_};
      p.motor_temp_c = motor_temp_c_;
      p.battery_temp_c = battery_temp_c_;
    }
    bus_.publish<ipc::MsgId::ThermalData>(p);
  }

 private:
  ipc::MessageBus& bus_;
  ComponentLogger logger_;
  std::mutex mu_;

  float ambient_temp_c_{20.0f};
  float motor_temp_c_{20.0f};
  float battery_temp_c_{20.0f};
};

}  // namespace sil
