#include "services/thermal_service.h"

#include <cmath>

namespace sil {

ThermalService::ThermalService(ipc::MessageBus& bus) : bus_(bus), logger_("thermal") {

}

void ThermalService::on_message(const PhysicsTickPayload& tick) {
  std::lock_guard lk{mu_};
  float dt_s = tick.dt_us / 1e6f;

  // Heat generated by motor based on RPM
  float motor_heat_rate = std::abs(tick.speed_rpm) * 0.05f;  // Increased 10x
  // Heat dissipated to environment
  float motor_cooling_rate = (motor_temp_c_ - ambient_temp_c_) * 0.05f;

  motor_temp_c_ += (motor_heat_rate - motor_cooling_rate) * dt_s;

  // Battery heat generated by current draw (simplistic approx based on RPM)
  float battery_heat_rate = std::abs(tick.speed_rpm) * 0.02f;  // Increased 10x
  float battery_cooling_rate = (battery_temp_c_ - ambient_temp_c_) * 0.02f;

  battery_temp_c_ += (battery_heat_rate - battery_cooling_rate) * dt_s;

  static uint32_t count = 0;
  if (++count % 100 == 0) {
    logger_.info("Motor Temp: %.1fC, Battery Temp: %.1fC", motor_temp_c_, battery_temp_c_);
  }
}

void ThermalService::on_message(const EnvironmentPayload& env) {
  std::lock_guard lk{mu_};
  ambient_temp_c_ = env.ambient_temp_c;
}

void ThermalService::on_message(const ThermalRequestPayload&) {
  publish_data();
}

void ThermalService::publish_data() {
  ThermalPayload p{};
  {
    std::lock_guard lk{mu_};
    p.motor_temp_c = motor_temp_c_;
    p.battery_temp_c = battery_temp_c_;
  }
  bus_.publish<MsgId::ThermalData>(p);
}

}  // namespace sil
